name = "ITensor_iMPS"
uuid = "e50fe4c1-d3f3-4f77-add5-1cddaf06af5c"
authors = ["QZ Zhu <123799445+QZ292@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Arpack = "0.5.4"
ITensors = "0.9.5"
LinearAlgebra = "1.11.0"
